### ISSUE TITLE
Support for multiple types

### ISSUE THREAD

**Issue by L2jLiga** [fastify/fastify-swagger#190]
When I tried to define type in schema like

```
{ type: ["string", "null"] }
```

Then I see in swagger:
```
"Unknown Type: string,null"
```

**Comment by mcollina** [comment]
This should work, maybe you would like to send a PR to fix this?

**Comment by L2jLiga** [comment]
I can try

**Comment by Eomm** [comment]
This plugin works with swagger2 (OAS2) and the null type doesn't exist in [that version](https://swagger.io/specification/v2/). OAS3 has been introduced the `nullable` field for this purpose.

So I think you could archive this only with the static registration using an OAS3 file.
The `dynamic` registration (that I started to explore.. but no time to complete) need a refactor in order to generate an OAS3 descriptor because, right now, it produces an OAS2 configuration.

**Comment by gwn** [comment]
I'm getting errors with `{ type: ["string", "number"] }` as well: `Unknown Type: string,number`

It looks like the value of the `type` key is stringified (note the comma between), so this may indicate that arrays aren't being handled. I may look more into this and submit a PR if I can find the time..

**Comment by mcollina** [comment]
This module definitely needs some love!

Il giorno mer 31 lug 2019 alle 17:11 gwn <notifications@github.com> ha
scritto:

**Comment by JacopoDaeli** [comment]
Yep. +1 on this as well. Will look into this ASAP.

**Comment by vikasg603** [comment]
Hey, any update on this?
This still gives the error.

**Comment by vikasg603** [comment]
Able to resolved this if we wanted to use null.
We can pass nullable: true to indicate schema can be nullable.

If anyone using https://github.com/ThomasAribart/json-schema-to-ts
I added a pr here: https://github.com/ThomasAribart/json-schema-to-ts/pull/37

**Comment by valerioleo** [comment]
I can confirm that this error is still happening on 4.12.6
a JSON Schema containing

```
 "collectionName": {
          "type": [
            "null",
            "string"
          ]
        }
```

results in `"Unknown Type: null,string"`
