### ISSUE TITLE
"Examples" incorrectly rendered for OpenAPI 3.x spec 

### ISSUE THREAD

**Issue by maolimu** [fastify/fastify-swagger#535]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Plugin version

4.13.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2 (21D49)

### Description

When adding an examples array to JSON Schema, when translating it to OpenAPI 3.x spec, the property seems to be misplaced: it is added under schemas but it should be next to it.

This causes a validation error in Swagger Editor, indicating the **examples** is not a valid property under **schemas** and it makes Swagger-UI not render the examples array.

### Steps to Reproduce

1) the schema is created with TypeBox
```typescript
export const PrototypesSchema = Type.Object(
    {
        foo: Type.String(),
        bar: Nullable(Type.String()),
    },
    {
        examples: [
            {
                foo: 'example 1',
                bar: null,
            },
            {
                foo: 'example 2',
                bar: 'some bar value',
            },
        ],
    }
);
```
2) the generated JSON-Schema is correct:
```json
{
   "examples": [
      {
         "foo": "example 1",
         "bar": null
      },
      {
         "foo": "example 2",
         "bar": "some bar value"
      }
   ],
   "type": "object",
   "properties": {
      "foo": {
         "type": "string"
      },
      "bar": {
         "type": "string",
         "nullable": true
      }
   },
   "required": [
      "foo",
      "bar"
   ]
}
```
3) The generated OpenAPI spec shows a validation error in Swagger Editor
```
Structural error at paths./experiments.put.requestBody.content.application/json.schema
should NOT have additional properties
additionalProperty: examples
Jump to line 29 
```

Indeed, the examples object is placed **below** schemas, but it should be **next** to it 
```yml
paths:
  /experiments:
    put:
      summary: experiments endpoint
      tags:
        - Misc
      requestBody:
        content:
          application/json:
            schema:
              examples:
                example1:
                  value:
                    foo: example 1
                    bar: null
                example2:
                  value:
                    foo: example 2
                    bar: some bar value
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: string
                  nullable: true
              required:
                - foo
                - bar
                - ```

### Expected Behavior

Place **examples** one level up, next to **schemas**, where it is correct

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mikicho** [comment]
Is `examples` an official keyword in json-schema? 
If yes, how should we treat nested examples like:
```
{
  examples: [ 1 ],
  type: 'object',
  properties: {
    a: {
      examples: [ 'a', 'b' ],
      type: 'string'
    },
    b: {
      examples: [ 'c', 'd' ],
      type: 'object',
      properties: { c: { type: 'string' } },
      required: [ 'c' ]
    }
  },
  required: [ 'a', 'b' ]
}
```

I'm not sure about the correct behaviour we need to implement here

**Comment by AlexVDW** [comment]
Hey @mikicho 

`examples` is a keyword defined by JSON schema as of draft 6; you can read about it [here](http://json-schema.org/understanding-json-schema/reference/generic.html). 

`examples` is _also_ a keyword in OpenAPI 3.x, which you can read about [here](https://swagger.io/docs/specification/adding-examples/). Note:

> Note that schemas and properties support single example but not multiple examples.

So, perhaps frustratingly, nested `examples` is not permitted. It looks like in general, **fastify-swagger** doesn't care if the user inserts incorrect keys into their schema, so I think nested examples should just be ignored.

Onto the fix for the initial problem, is it enouh

**Comment by AlexVDW** [comment]
Hey @mikicho 

`examples` is a keyword defined by JSON schema as of draft 6; you can read about it [here](http://json-schema.org/understanding-json-schema/reference/generic.html). 

`examples` is _also_ a keyword in OpenAPI 3.x, which you can read about [here](https://swagger.io/docs/specification/adding-examples/). Note:

> Note that schemas and properties support single example but not multiple examples.

So, perhaps frustratingly, nested `examples` is not permitted. It looks like in general, **fastify-swagger** doesn't care if the user inserts incorrect keys into their schema, so I think nested examples should just be ignored.

Onto the fix for the initial problem, is it enough to simply move the `examples` property from the `schema` object to the next level up? This would mean that this:

```typescript
fastify.get('/description', {
  schema: {
    response: {
      200: {
        type: 'string',
        examples: ['one', 'two'],
      }
    }
  }
}, () => {})
```
gives something like
```json
"get": {
  "responses": {
    "200": {
      "description": "Default Response",
      "content": {
        "application/json": {
          "schema": {
            "type": "string",
            "examples": {
              "one": {
                "value": "one"
              },
              "two": {
                "value": "two"
              }
            }
          }
        }
      }
    }
  }
},
```

It gets a bit weird when using `$ref`s and something like TypeBox; I'd be doing something like:
```javascript
export const PrototypesSchema = Type.Object(
    {
        foo: Type.String(),
        bar: Nullable(Type.String()),
    },
    {
        examples: [
            {
                foo: 'example 1',
                bar: null,
            },
            {
                foo: 'example 2',
                bar: 'some bar value',
            },
        ],
    }
);
```
to generate the schema, then
```javascript
fastify.addSchema(PrototypesSchema)
// ...
fastify.get('/description', {
  schema: {
    200: {
        ...Type.Ref(PrototypesSchema),
        examples: [
            {
                foo: 'example 1',
                bar: null,
            },
            {
                foo: 'example 2',
                bar: 'some bar value',
            },
        ],
      },
  }
}, () => {})
```

Would it be more correct if **fastify-swagger** used a `x-examples` keyword instead of `examples`, since it is manipulating the schema after user implementation (much like `x-response-description`)

______

As a side note, currently `examples` takes an array (enforced by JSON Schema) and is outputted as an object. The property names are created by **fastify-swagger**; is there any way to define these? Perhaps `x-examples` (if implemented) could take a literal object of the examples
