### ISSUE TITLE
how to add binary file as request body?

### ISSUE THREAD

**Issue by gusparr28** [fastify/fastify-swagger#698]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by gusparr28** [comment]
I have an endpoint that receives binary file in request body. How to add that spec to Fastify Swagger? I've been through the docs and different issues and haven't found a clear solution. Appreciated. Thanks

**Comment by Uzlopak** [comment]
https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by climba03003** [comment]
> https://swagger.io/docs/specification/describing-request-body/file-upload/

Pasting `Swagger` link do not helps in any case. We transform `JSON Schema` to `API Docs` which require users to pass proper `JSON Schema`.

If you need to use `formdata`.
`{ type: 'string', format: 'binary' }` would do the trick, but you should remove the `validator`. Since `ajv` DO NOT support `binary`.
